### ISSUE TITLE
Checklist for CSI integration

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#1075]
## Controller

- CreateVolume
    - [x] Support for MountVolume create
    - [ ] Support For BlockVolume Create
    - [ ] Support for Create Volume from a Snapshot(Snapshot Clone)

- Delete Volume: 
    - [x] Support for delete Volume
    - [ ] Support for delete bricks/lv

- ControllerPublishVolume
- ControllerUnpublishVolume
- ValidateVolumeCapabilities
- ListVolumes
    - [x] List Volumes
- GetCapacity
    - [ ] API to get used and available size based on default Volume type(Replica 3)

- ControllerGetCapabilities
- CreateSnapshot
    - [x] Support for Volume snapshot
    - [ ] Support for BlockVolume Snapshot

- DeleteSnapshot
    - [x] Support for Volume snapshot delete
    - [ ] Support for Block Volume snapshot delete

- ListSnapshots
    - [x] List Volume Snapshots
    - [ ] List Block Volume Snapshots

## Node
Below functionalities are mostly using mount command to Stage/Publish and unmount command to Unstage/Unpublish the volume in required node/pod

- NodeStageVolume
- NodeUnstageVolume
- NodePublishVolume
- NodeUnpublishVolume
- NodeGetId
- NodeGetCapabilities
- NodeGetInfo

From gd2,
- [x] gd2 RPC to fetch Volfile for mount
- [ ] Security/TLS

Please add if any more APIs needed for CSI integration

**Comment by amarts** [comment]
Looks like the issue covers topic for 2 CSI. Each CSI deals with just one type of StorageClass. Above talks about Both File Volume (ie, regular gluster volume) and BlockVolume (ie, gluster-block volume).

We can consider it as two different issues IMO. The list looks comprehensive though.

@raghavendra-talur @JohnStrunk
