### ISSUE TITLE
Checklist of gd1 commands

### ISSUE THREAD

**Issue by amarts** [gluster/glusterd2#609]
## Top level options

- [ ] - peer help                - display help for peer commands
- [ ] - volume help              - display help for volume commands
- [ ] - volume bitrot help       - display help for volume bitrot commands
- [ ] - volume quota help        - display help for volume quota commands
- [ ] - volume tier help         - display help for volume tier commands
- [ ] - snapshot help            - display help for snapshot commands
- [ ] - global help              - list global commands

### gluster peer commands
- [ ] - peer detach { <HOSTNAME> | <IP-address> } [force] - detach peer specified by <HOSTNAME>
- [ ] - peer help - display help for peer commands
- [ ] - peer probe { <HOSTNAME> | <IP-address> } - probe peer specified by <HOSTNAME>
- [ ] - peer status - list status of peers
- [ ] - pool list - list all the nodes in the pool (including localhost)

### gluster volume commands
- [ ] - volume add-brick <VOLNAME> [<stripe|replica> <COUNT> [arbiter <COUNT>]] <NEW-BRICK> ... [force] - add brick to volume <VOLNAME>
- [ ] - volume barrier <VOLNAME> {enable|disable} - Barrier/unbarrier file operations on a volume
- [ ] - volume clear-locks <VOLNAME> <path> kind {blocked|granted|all}{inode [range]|entry [basename]|posix [range]} - Clear locks held on path
- [ ] - volume create <NEW-VOLNAME> [stripe <COUNT>] [replica <COUNT> [arbiter <COUNT>]] [disperse [<COUNT>]] [disperse-data <COUNT>] [redundancy <COUNT>] [transport <tcp|rdma|tcp,rdma>] <N\
EW-BRICK>... [force] - create a new volume of specified type with mentioned bricks
- [ ] - volume delete <VOLNAME> - delete volume specified by <VOLNAME>
- [ ] - volume geo-replication [<VOLNAME>] [<SLAVE-URL>] {create [[ssh-port n] [[no-verify]|[push-pem]]] [force]|start [force]|stop [force]|pause [force]|resume [force]|config|status [detai\
l]|delete [reset-sync-time]} [options...] - Geo-sync operations
- [ ] - volume get <VOLNAME|all> <key|all> - Get the value of the all options or given option for volume <VOLNAME> or all option. gluster volume get all all is to get all global options
- [ ] - volume heal <VOLNAME> [enable | disable | full |statistics [heal-count [replica <HOSTNAME:BRICKNAME>]] |info [summary | split-brain] |split-brain {bigger-file <FILE> | latest-mtime \
<FILE> |source-brick <HOSTNAME:BRICKNAME> [<FILE>]} |granular-entry-heal {enable | disable}] - self-heal commands on volume specified by <VOLNAME>
- [ ] - volume help - display help for volume commands
- [ ] - volume info [all|<VOLNAME>] - list information of all volumes
- [ ] - volume list - list all volumes in cluster
- [ ] - volume log <VOLNAME> rotate [BRICK] - rotate the log file for corresponding volume/brick
- [ ] - volume log rotate <VOLNAME> [BRICK] - rotate the log file for corresponding volume/brick NOTE: This is an old syntax, will be deprecated from next release.
- [ ] - volume profile <VOLNAME> {start|info [peek|incremental [peek]|cumulative|clear]|stop} [nfs] - volume profile operations
- [ ] - volume rebalance <VOLNAME> {{fix-layout start} | {start [force]|stop|status}} - rebalance operations
- [ ] - volume remove-brick <VOLNAME> [replica <COUNT>] <BRICK> ... <start|stop|status|commit|force> - remove brick from volume <VOLNAME>
- [ ] - volume replace-brick <VOLNAME> <SOURCE-BRICK> <NEW-BRICK> {commit force} - replace-brick operations
- [ ] - volume reset <VOLNAME> [option] [force] - reset all the reconfigured options
- [ ] - volume reset-brick <VOLNAME> <SOURCE-BRICK> {{start} | {<NEW-BRICK> commit}} - reset-brick operations
- [ ] - volume set <VOLNAME> <KEY> <VALUE> - set options for volume <VOLNAME>
- [ ] - volume start <VOLNAME> [force] - start volume specified by <VOLNAME>
- [ ] - volume statedump <VOLNAME> [[nfs|quotad] [all|mem|iobuf|callpool|priv|fd|inode|history]... | [client <hostname:process-id>]] - perform statedump on bricks
- [ ] - volume status [all | <VOLNAME> [nfs|shd|<BRICK>|quotad|tierd]] [detail|clients|mem|inode|fd|callpool|tasks|client-list] - display status of all or specified volume(s)/brick
- [ ] - volume stop <VOLNAME> [force] - stop volume specified by <VOLNAME>
- [ ] - volume sync <HOSTNAME> [all|<VOLNAME>] - sync the volume information from a peer
- [ ] - volume top <VOLNAME> {open|read|write|opendir|readdir|clear} [nfs|brick <brick>] [list-cnt <value>] |
- [ ] - volume top <VOLNAME> {read-perf|write-perf} [bs <size> count <count>] [brick <brick>] [list-cnt <value>] - volume top operations

### gluster bitrot commands
- [ ] - volume bitrot <VOLNAME> scrub {pause|resume|status|ondemand} - Pause/resume the scrubber for <VOLNAME>. Status displays the status of the scrubber. ondemand starts the scrubber imme\
diately.
- [ ] - volume bitrot <VOLNAME> scrub-frequency {hourly|daily|weekly|biweekly|monthly} - Set the frequency of the scrubber for volume <VOLNAME>
- [ ] - volume bitrot <VOLNAME> scrub-throttle {lazy|normal|aggressive} - Set the speed of the scrubber for volume <VOLNAME>
- [ ] - volume bitrot <VOLNAME> {enable|disable} - Enable/disable bitrot for volume <VOLNAME>
- [ ] - volume bitrot help - display help for volume bitrot commands

### gluster quota commands
- [ ] - volume inode-quota <VOLNAME> enable - Enable/disable inode-quota for <VOLNAME>
- [ ] - volume quota <VOLNAME> {alert-time|soft-timeout|hard-timeout} {<time>} - Set quota timeout for <VOLNAME>
- [ ] - volume quota <VOLNAME> {enable|disable|list [<path> ...]| list-objects [<path> ...] | remove <path>| remove-objects <path> | default-soft-limit <percent>} - Enable/disable and confi\
gure quota for <VOLNAME>
- [ ] - volume quota <VOLNAME> {limit-objects <path> <number> [<percent>]} - Set the maximum number of entries allowed in <path> for <VOLNAME>
- [ ] - volume quota <VOLNAME> {limit-usage <path> <size> [<percent>]} - Set maximum size for <path> for <VOLNAME>
- [ ] - volume quota help - display help for volume quota commands

### gluster tier commands
- [ ] - volume attach-tier <VOLNAME> [<replica COUNT>] <NEW-BRICK>... - NOTE: this is old syntax, will be deprecated in next release. Please use gluster volume tier <vol> attach [<replica C\
OUNT>] <NEW-BRICK>...
- [ ] - volume detach-tier <VOLNAME> <start|stop|status|commit|force> - NOTE: this is old syntax, will be deprecated in next release. Please use gluster volume tier <vol> detach {start|stop\
|commit} [force]
- [ ] - volume tier <VOLNAME> attach [<replica COUNT>] <NEW-BRICK>... [force] - Attach a hot tier to <VOLNAME>
- [ ] - volume tier <VOLNAME> detach <start|stop|status|commit|[force]> - Detach the hot tier from <VOLNAME>
- [ ] - volume tier <VOLNAME> start [force] - Start the tier service for <VOLNAME>
- [ ] - volume tier <VOLNAME> status - Display tier status for <VOLNAME>
- [ ] - volume tier <VOLNAME> stop [force] - Stop the tier service for <VOLNAME>
- [ ] - volume tier help - display help for volume tier commands

### gluster snapshot commands
- [ ] - snapshot activate <snapname> [force] - Activate snapshot volume.
- [ ] - snapshot clone <clonename> <snapname> - Snapshot Clone.
- [ ] - snapshot config [volname] ([snap-max-hard-limit <count>] [snap-max-soft-limit <percent>]) | ([auto-delete <enable|disable>])| ([activate-on-create <enable|disable>]) - Snapshot Conf\
ig.
- [ ] - snapshot create <snapname> <volname> [no-timestamp] [description <description>] [force] - Snapshot Create.
- [ ] - snapshot deactivate <snapname> - Deactivate snapshot volume.
- [ ] - snapshot delete (all | snapname | volume <volname>) - Snapshot Delete.
- [ ] - snapshot help - display help for snapshot commands
- [ ] - snapshot info [(snapname | volume <volname>)] - Snapshot Info.
- [ ] - snapshot list [volname] - Snapshot List.
- [ ] - snapshot restore <snapname> - Snapshot Restore.
- [ ] - snapshot status [(snapname | volume <volname>)] - Snapshot Status.

### gluster global commands

- [ ] - get-state [<daemon>] [[odir </path/to/output/dir/>] [file <filename>]] [detail|volumeoptions] - Get local state representation of mentioned daemon
- [ ] - global help - list global commands

**Comment by amarts** [comment]
As there are not many active members supporting `tier` feature, totally OK to consider not have those feature initially with GD2.

**Comment by atinmu** [comment]
Placeholder for checking the parity. To be completed by GlusterFS 4.3.
