### ISSUE TITLE
Address comments and TODO in snapshot implementation 

### ISSUE THREAD

**Issue by rafikc30** [gluster/glusterd2#831]
There are a couple of comments that need to address along with TODO to finish the snapshot basic features. This issue is to track those PRs.

**Comment by rafikc30** [comment]
- [ ]  config options
        * activate-on-create
        * hard-limit a d soft-limit
        * auto-delete
- [ ]  copy quotad configuration during snapshot create
- [ ]  Label based snapshots
- [ ]  copy geo-replication configuration during snapshot create
- [ ]  check for rebalance status during snapshot create (Need to have a common snapshot check api)
- [ ]  High Availibility for snapshots
- [ ]  Create lvm as an inerface so that other fs can be easily plugged
- [ ]  Check for lvm size restrictions during snapshot create
- [ ]  Snapshot scheduler
- [ ]  Healing of snapshot bricks
- [ ]  Add brick/Replace brick on snapshotted volumes

**Comment by atinmu** [comment]
I don't think all of these items are GCS blockers. We need to filter out the blocker ones from this and tag the respective issues.

**Comment by rafikc30** [comment]
Separate tracker is created for issues that have not finished yet. So closing the issue.
